class OrderPageLocators:
    NAME_INPUT = ("xpath", "//input[@placeholder='* Имя']")
    SURNAME_INPUT = ("xpath", "//input[@placeholder='* Фамилия']")
    ADDRESS_INPUT = ("xpath", "//input[@placeholder='* Адрес: куда привезти заказ']")
    METRO_INPUT = ("xpath", "//input[@placeholder='* Станция метро']")
    FIRST_METRO_STATION = ("xpath", "//li[@data-index='0']")
    PHONE_INPUT = ("xpath", "//input[@placeholder='* Телефон: на него позвонит курьер']")
    NEXT_BUTTON = ("xpath", "//button[text()='Далее']")
    DATE_INPUT = ("xpath", "//input[@placeholder='* Когда привезти самокат']")
    TODAY_DATE = ("xpath", "//div[contains(@class, 'react-datepicker__day--today')]")
    RENTAL_PERIOD = ("xpath", "//div[text()='* Срок аренды']")
    PERIOD_DAY = ("xpath", "//div[text()='сутки']")
    BLACK_COLOR = ("id", "black")
    COMMENT_INPUT = ("xpath", "//input[@placeholder='Комментарий для курьера']")
    ORDER_BUTTON = ("xpath", "(//button[text()='Заказать'])[2]")
    CONFIRM_BUTTON = ("xpath", "//button[text()='Да']")
    SUCCESS_MODAL = ("xpath", "//div[contains(text(), 'Заказ оформлен')]")